# Email Spam Detection

This program detects if an email is spam or not

In [ ]:
# Importing Libraries 

In [ ]:
import numpy as np
import pandas as pd
import nltk 
from nltk.corpus import stopwords
import string

In [ ]:
df=pd.read_csv("emails.csv")

In [ ]:
df.info()

In [ ]:
df.head(10)

In [ ]:
df.shape

In [ ]:
df.columns

# Checking for duplicates and remove them

In [ ]:
df.drop_duplicates(inplace=True)


In [ ]:
#showing the new shape after removing the duplicates

In [ ]:
df.shape 

# Number of missing Data 

In [ ]:
df.isnull().sum()

So there is no missing data 

# Download the stopwords 

In [ ]:
nltk.download("stopwords")

In [ ]:
def process_text(text):
    #1 remove punctuation
    #2 remove stopwords
    #3 return a list of clean text words
    
    
    #1
    nopunc =[char for char in text if char not in string.punctuation]
    nopunc= "".join(nopunc)
    #2
    clean_words=[word for word in nopunc.split() if word.lower() not in stopwords.words("english")] 
    #3
    return clean_words

# Show the tokenization (a list of tokens also called lemmas)

In [ ]:
df["text"].head(5).apply(process_text)

here massages are borken up and each words are separated by comma

# Example 

In [ ]:
message4= "hello world hello hello hello play"
message5= "test test test test one hello"
print(message4)
print()

# convert the text to matrix of token count 
from sklearn.feature_extraction.text import CountVectorizer
bow4 = CountVectorizer(analyzer=process_text).fit_transform([[message4],[message5]])
print(bow4)
print()
print(bow4.shape)

# Convert a collection of text to a matrix of tokens

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
messages_bow = CountVectorizer(analyzer=process_text).fit_transform(df["text"])

# Spliting the data into 80% training and 20% testing 

In [59]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test =train_test_split(messages_bow,df["spam"],test_size=0.20,random_state=0)

In [60]:
messages_bow.shape

(5695, 37229)

# Creating Naive Bayes Classifier

In [63]:
from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB().fit(x_train,y_train)

In [64]:
print(classifier.predict(x_train))

[0 0 0 ... 0 0 0]


In [88]:
print(y_train.values)

[0 0 0 ... 0 0 0]


# Evaluating the model on the training data set

In [81]:
from sklearn.metrics import classification_report, confusion_matrix,accuracy_score


In [87]:
pred = classifier.predict(x_train)
print(classification_report(y_train,pred))
print()
print("Confusion Matrix \n", confusion_matrix (y_train,pred))
print ()
print("Accurcy: ", accuracy_score(y_train,pred))
print()

              precision    recall  f1-score   support

           0       1.00      1.00      1.00      3457
           1       0.99      1.00      0.99      1099

    accuracy                           1.00      4556
   macro avg       0.99      1.00      1.00      4556
weighted avg       1.00      1.00      1.00      4556


Confusion Matrix 
 [[3445   12]
 [   1 1098]]

Accurcy:  0.9971466198419666



In [89]:
print(classifier.predict(x_test))
print(y_test.values)

[1 0 0 ... 0 0 0]
[1 0 0 ... 0 0 0]


In [90]:
pred = classifier.predict(x_test)
print(classification_report(y_test,pred))
print()
print("Confusion Matrix \n", confusion_matrix (y_test,pred))
print ()
print("Accurcy: ", accuracy_score(y_test,pred))
print()

              precision    recall  f1-score   support

           0       1.00      0.99      0.99       870
           1       0.97      1.00      0.98       269

    accuracy                           0.99      1139
   macro avg       0.98      0.99      0.99      1139
weighted avg       0.99      0.99      0.99      1139


Confusion Matrix 
 [[862   8]
 [  1 268]]

Accurcy:  0.9920983318700615

